<?php
$labels = array();
$labels['pluginname'] = 'Připojení karty vCard';
$labels['plugindescription'] = 'K odchozím zprávám můžete připojit svou kartu vCard.';
$labels['attachvcard'] = 'Připojení karty vCard';
$labels['from'] = 'Použijte data vCard z ...';
$labels['warning'] = 'Upozornění: Při výběru možnosti "Kontakt" budete spolu s kartou vCard odesílat soukromé informace, jako jsou vaše narozeniny, soukromý telefon, mobilní telefon, fotografie atd. Před odesláním karty vCard připojené k e-mailům se ujistěte, že jste vyplnili kontaktní údaje karty vCard pouze informacemi, které jste ochotni sdílet.';
?>
