<?php
$labels = array();
$labels['pluginname'] = 'Vedhæft vCard';
$labels['plugindescription'] = 'Vedhæft dit vCard til udgående beskeder.';
$labels['attachvcard'] = 'Vedhæft vCard';
$labels['from'] = 'Brug vCard-data fra ...';
$labels['warning'] = 'Bemærk: Når du vælger indstillingen "Kontakt", sender du private oplysninger med dit vCard, f.eks. din fødselsdag, private telefon, mobil, foto osv. Sørg for kun at udfylde dit vCards kontaktoplysninger med de oplysninger, du er villig til at dele, før du sender dit vCard vedhæftet til e-mails.';
?>
