<?php
$labels = array();
$labels['pluginname'] = 'VCard anhängen';
$labels['plugindescription'] = 'Hängen Sie Ihre vCard an ausgehende Nachrichten an.';
$labels['attachvcard'] = 'VCard anhängen';
$labels['from'] = 'Verwenden Sie vCard-Daten aus ...';
$labels['warning'] = 'Bitte beachten Sie: Wenn Sie die Option "Kontakt" wählen, senden Sie private Informationen mit Ihrer vCard, wie z. B. Ihren Geburtstag, Ihre private Telefonnummer, Ihr Handy, Ihr Foto usw. Stellen Sie sicher, dass Sie die Kontaktdaten Ihrer vCard nur mit den Informationen ausfüllen, die Sie bereit sind zu teilen, bevor Sie Ihre vCard als Anhang einer E-Mail versenden.';
?>
