<?php
$labels = array();
$labels['pluginname'] = 'Adjuntar vCard';
$labels['plugindescription'] = 'Adjunta tu vCard a los mensajes salientes.';
$labels['attachvcard'] = 'Adjuntar vCard';
$labels['from'] = 'Utiliza datos vCard de ...';
$labels['warning'] = 'Nota: Al seleccionar la opción "Contacto" estará enviando información privada con su vCard, como su cumpleaños, teléfono privado, móvil, foto, etc. Asegúrese de rellenar los datos de contacto de su vCard sólo con la información que esté dispuesto a compartir antes de enviar su vCard adjunta a los correos electrónicos.';
?>
