<?php
$labels = array();
$labels['pluginname'] = 'Lisa vCard';
$labels['plugindescription'] = 'Lisage oma vCard väljaminevatele sõnumitele.';
$labels['attachvcard'] = 'Lisa vCard';
$labels['from'] = 'Kasutage vCard andmeid ...';
$labels['warning'] = 'Pange tähele: Kui valite valiku "Kontakt", saadate oma vCardiga privaatset teavet, nagu teie sünnipäev, isiklik telefon, mobiiltelefon, foto jne. Veenduge, et täidate oma vCard\'i kontaktandmed ainult sellise teabega, mida olete nõus jagama, enne kui saadate oma vCard\'i e-kirjadele manustatuna välja.';
?>
