<?php
$labels = array();
$labels['pluginname'] = 'Liitä vCard';
$labels['plugindescription'] = 'Liitä vCard-korttisi lähteviin viesteihin.';
$labels['attachvcard'] = 'Liitä vCard';
$labels['from'] = 'Käytä vCard-tietoja ...';
$labels['warning'] = 'Huomaa: Kun valitset "Yhteystiedot"-vaihtoehdon, lähetät vCard-korttisi mukana yksityisiä tietoja, kuten syntymäpäiväsi, yksityinen puhelinnumerosi, matkapuhelimesi, valokuvasi jne. Varmista, että täytät vCardin yhteystietoihin vain ne tiedot, jotka olet valmis jakamaan, ennen kuin lähetät vCardin sähköpostin liitteenä.';
?>
