<?php
$labels = array();
$labels['pluginname'] = 'Joindre une vCard';
$labels['plugindescription'] = 'Joignez votre vCard aux messages sortants.';
$labels['attachvcard'] = 'Joindre une vCard';
$labels['from'] = 'Utilisez les données vCard de ...';
$labels['warning'] = 'Remarque : lorsque vous sélectionnez l\'option "Contact", vous envoyez des informations privées avec votre vCard, telles que votre date d\'anniversaire, votre numéro de téléphone privé, votre numéro de portable, votre photo, etc. Veillez à ne remplir les coordonnées de votre vCard qu\'avec les informations que vous souhaitez partager avant d\'envoyer votre vCard en pièce jointe d\'un courrier électronique.';
?>
