<?php
$labels = array();
$labels['pluginname'] = 'צרף vCard';
$labels['plugindescription'] = 'צרף את כרטיס ה-vCard שלך להודעות יוצאות.';
$labels['attachvcard'] = 'צרף vCard';
$labels['from'] = 'השתמש בנתוני vCard מ...';
$labels['warning'] = 'שימו לב: בבחירת האפשרות "צור קשר" תשלחו מידע פרטי עם כרטיס ה-vCard שלכם, כגון תאריך לידה, מספר טלפון פרטי, מספר טלפון נייד, תמונה וכו\'. הקפידו למלא את פרטי הקשר בכרטיס ה-vCard רק במידע שאתם מעוניינים לשתף לפני שתשלחו את כרטיס ה-vCard המצורף לדוא"ל.';
?>
