<?php
$labels = array();
$labels['pluginname'] = 'VCard csatolása';
$labels['plugindescription'] = 'Csatolja vCard kártyáját a kimenő üzenetekhez.';
$labels['attachvcard'] = 'VCard csatolása';
$labels['from'] = 'Használja a vCard adatokat ...';
$labels['warning'] = 'Megjegyzés: Ha a "Kapcsolat" opciót választja, akkor a vCard-dal együtt olyan személyes adatokat küld, mint a születésnapja, a privát telefonszáma, a mobiltelefonja, a fényképe stb. Győződjön meg róla, hogy a vCard elérhetőségi adatait csak azokkal az információkkal tölti ki, amelyeket hajlandó megosztani, mielőtt elküldi vCardját e-mailhez csatolva.';
?>
