<?php
$labels = array();
$labels['pluginname'] = 'Memasang vCard';
$labels['plugindescription'] = 'Lampirkan vCard Anda ke pesan keluar.';
$labels['attachvcard'] = 'Memasang vCard';
$labels['from'] = 'Gunakan data vCard dari ...';
$labels['warning'] = 'Harap diperhatikan: Ketika memilih opsi "Kontak", Anda akan mengirimkan informasi pribadi dengan vCard Anda seperti ulang tahun, telepon pribadi, ponsel, foto, dll. Pastikan untuk mengisi detail kontak vCard Anda hanya dengan informasi yang ingin Anda bagikan sebelum mengirimkan vCard yang dilampirkan ke email.';
?>
