<?php
$labels = array();
$labels['pluginname'] = 'Allegare la vCard';
$labels['plugindescription'] = 'Allegare la vCard ai messaggi in uscita.';
$labels['attachvcard'] = 'Allegare la vCard';
$labels['from'] = 'Utilizzare i dati vCard da ...';
$labels['warning'] = 'Nota bene: selezionando l\'opzione "Contatto", si invieranno informazioni private con la vCard, come compleanno, telefono privato, cellulare, foto, ecc. Assicuratevi di compilare i dati di contatto della vCard solo con le informazioni che siete disposti a condividere prima di inviare la vCard allegata alle e-mail.';
?>
