<?php
$labels = array();
$labels['pluginname'] = 'Pridėti "vCard';
$labels['plugindescription'] = 'Pridėkite "vCard" prie išeinančių pranešimų.';
$labels['attachvcard'] = 'Pridėti "vCard';
$labels['from'] = 'Naudokite "vCard" duomenis iš ...';
$labels['warning'] = 'Atkreipkite dėmesį: pasirinkę parinktį "Kontaktai", kartu su "vCard" siųsite privačią informaciją, pvz., savo gimtadienį, asmeninį telefoną, mobilųjį telefoną, nuotrauką ir pan. Prieš siųsdami prie el. laiškų prisegtą "vCard", būtinai užpildykite "vCard" kontaktinę informaciją tik ta informacija, kuria norite dalytis.';
?>
