<?php
$labels = array();
$labels['pluginname'] = 'Pievienojiet vCard';
$labels['plugindescription'] = 'Pievienojiet vCard izejošajiem ziņojumiem.';
$labels['attachvcard'] = 'Pievienojiet vCard';
$labels['from'] = 'Izmantojiet vCard datus no ...';
$labels['warning'] = 'Lūdzu, ņemiet vērā: izvēloties opciju "Kontaktpersona", kopā ar vCard karti nosūtīsiet privātu informāciju, piemēram, savu dzimšanas dienu, privāto tālruni, mobilo tālruni, fotoattēlu u. c. Pirms sūtīt e-pasta ziņojumiem pievienoto vCard, pārliecinieties, ka esat aizpildījis vCard kontaktpersonas kontaktinformāciju tikai ar to informāciju, ar kuru vēlaties dalīties.';
?>
