<?php
$labels = array();
$labels['pluginname'] = 'VCard bijvoegen';
$labels['plugindescription'] = 'Voeg uw vCard toe aan uitgaande berichten.';
$labels['attachvcard'] = 'VCard bijvoegen';
$labels['from'] = 'Gebruik vCard-gegevens van ...';
$labels['warning'] = 'Let op: Als u de optie "Contact" selecteert, verzendt u privégegevens met uw vCard, zoals uw verjaardag, privételefoon, mobiele telefoon, foto, enz. Zorg ervoor dat u de contactgegevens van uw vCard alleen invult met de informatie die u wilt delen voordat u uw vCard als bijlage bij e-mails verstuurt.';
?>
