<?php
$labels = array();
$labels['pluginname'] = 'Legg ved vCard';
$labels['plugindescription'] = 'Legg ved vCard-kortet ditt i utgående meldinger.';
$labels['attachvcard'] = 'Legg ved vCard';
$labels['from'] = 'Bruk vCard-data fra ...';
$labels['warning'] = 'Merk: Når du velger alternativet "Kontakt", sender du privat informasjon med vCard-kortet ditt, for eksempel bursdag, privat telefon, mobil, bilde osv. Sørg for å fylle ut kontaktinformasjonen i vCardet ditt kun med den informasjonen du er villig til å dele før du sender ut vCardet ditt som vedlegg til e-post.';
?>
