<?php
$labels = array();
$labels['pluginname'] = 'Dołącz vCard';
$labels['plugindescription'] = 'Dołącz wizytówkę vCard do wiadomości wychodzących.';
$labels['attachvcard'] = 'Dołącz vCard';
$labels['from'] = 'Użyj danych vCard z ...';
$labels['warning'] = 'Uwaga: Wybierając opcję "Kontakt", będziesz wysyłać prywatne informacje wraz z wizytówką vCard, takie jak data urodzin, prywatny telefon, telefon komórkowy, zdjęcie itp. Upewnij się, że przed wysłaniem wizytówki vCard dołączonej do wiadomości e-mail wypełniłeś dane kontaktowe wizytówki vCard wyłącznie informacjami, które chcesz udostępnić.';
?>
