<?php
$labels = array();
$labels['pluginname'] = 'Anexar vCard';
$labels['plugindescription'] = 'Anexe seu vCard às mensagens enviadas.';
$labels['attachvcard'] = 'Anexar vCard';
$labels['from'] = 'Use dados vCard de ...';
$labels['warning'] = 'Observação: Ao selecionar a opção "Contato", você enviará informações particulares com o seu vCard, como data de aniversário, telefone particular, celular, foto etc. Certifique-se de preencher os detalhes de contato do seu vCard somente com as informações que deseja compartilhar antes de enviar o vCard anexado a e-mails.';
?>
