<?php
$labels = array();
$labels['pluginname'] = 'Atașați vCard';
$labels['plugindescription'] = 'Atașați-vă vCard-ul la mesajele de ieșire.';
$labels['attachvcard'] = 'Atașați vCard';
$labels['from'] = 'Utilizați datele vCard din ...';
$labels['warning'] = 'Vă rugăm să rețineți: Atunci când selectați opțiunea "Contact", veți trimite informații private împreună cu vCard-ul dvs., cum ar fi ziua dvs. de naștere, telefonul privat, telefonul mobil, fotografia etc. Asigurați-vă că completați datele de contact ale vCard-ului numai cu informațiile pe care sunteți dispus să le împărtășiți înainte de a trimite vCard-ul atașat la e-mailuri.';
?>
