<?php
$labels = array();
$labels['pluginname'] = 'Pripojiť kartu vCard';
$labels['plugindescription'] = 'Pripojte svoju kartu vCard k odchádzajúcim správam.';
$labels['attachvcard'] = 'Pripojiť kartu vCard';
$labels['from'] = 'Použite údaje vCard z ...';
$labels['warning'] = 'Upozornenie: Ak vyberiete možnosť "Kontakt", budete posielať súkromné informácie spolu s vašou kartou vCard, ako sú vaše narodeniny, súkromný telefón, mobil, fotografia atď. Pred odoslaním karty vCard pripojenej k e-mailom sa uistite, že ste vyplnili kontaktné údaje karty vCard len tými informáciami, ktoré chcete zdieľať.';
?>
