<?php
$labels = array();
$labels['pluginname'] = 'Priložite kartico vCard';
$labels['plugindescription'] = 'Odhodnim sporočilom priložite kartico vCard.';
$labels['attachvcard'] = 'Priložite kartico vCard';
$labels['from'] = 'Uporabite podatke vCard iz ...';
$labels['warning'] = 'Upoštevajte: z izbiro možnosti "Stik" boste v kartico vCard poslali zasebne podatke, kot so rojstni dan, zasebni telefon, mobilni telefon, fotografija itd. Preden pošljete svojo vCard, ki je priložena e-poštnim sporočilom, poskrbite, da v kontaktne podatke svoje vCard vpišete samo podatke, ki jih želite deliti.';
?>
