<?php
$labels = array();
$labels['pluginname'] = 'Bifoga vCard';
$labels['plugindescription'] = 'Bifoga ditt vCard till utgående meddelanden.';
$labels['attachvcard'] = 'Bifoga vCard';
$labels['from'] = 'Använd vCard-data från ...';
$labels['warning'] = 'Observera: När du väljer alternativet "Kontakt" kommer du att skicka privat information med ditt vCard, t.ex. födelsedag, privat telefon, mobil, foto osv. Se till att fylla i kontaktuppgifterna för ditt vCard endast med den information du är villig att dela med dig av innan du skickar ut ditt vCard som bilaga till e-postmeddelanden.';
?>
