<?php
$labels = array();
$labels['pluginname'] = 'VCard ekleyin';
$labels['plugindescription'] = 'Giden mesajlara vCard\'ınızı ekleyin.';
$labels['attachvcard'] = 'VCard ekleyin';
$labels['from'] = 'VCard verilerini kullanın ...';
$labels['warning'] = 'Lütfen dikkat: "İletişim" seçeneğini seçtiğinizde vCard\'ınızla birlikte doğum gününüz, özel telefonunuz, cep telefonunuz, fotoğrafınız vb. gibi özel bilgiler göndereceksiniz. VCard\'ınızı e-postalara ekli olarak göndermeden önce vCard\'ınızın iletişim bilgilerini yalnızca paylaşmak istediğiniz bilgilerle doldurduğunuzdan emin olun.';
?>
