<?php
$labels = array();
$labels['pluginname'] = 'Đính kèm vCard';
$labels['plugindescription'] = 'Đính kèm thẻ vCard vào các tin nhắn gửi đi.';
$labels['attachvcard'] = 'Đính kèm vCard';
$labels['from'] = 'Sử dụng dữ liệu vCard từ ...';
$labels['warning'] = 'Lưu ý: Khi chọn tùy chọn "Liên hệ", bạn sẽ gửi thông tin cá nhân kèm theo vCard của mình, bao gồm ngày sinh, số điện thoại cá nhân, số điện thoại di động, ảnh, v.v. Vui lòng chỉ điền thông tin liên hệ trong vCard của bạn với những thông tin mà bạn sẵn sàng chia sẻ trước khi gửi vCard kèm theo email.';
?>
